# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
script: 
  - |
    R CMD build --no-build-vignettes .
    travis_wait 40 R CMD check --no--vignettes sperrorest*tar.gz
